### PR TITLE
added basename to router if env var is defined

### PR DESCRIPTION
**Pull request by jordykirkman**
This modification allows for specifying a BASENAME env var, so routing still works even when deployed to a subdirectory. 

https://github.com/Flagsmith/flagsmith-frontend/issues/39

### CODE REVIEW

**Comment by dabeeeenster** [comment]
Awesome thanks! Can we get this added to the readme too?

**Comment by KOGI** [comment]
Readme added, btw

**Comment by kyle-ssg** [comment]
Merged, thanks!

**Comment by KOGI** [comment]
@kyle-ssg thanks for merging! When do you think (roughly) we can expect to see the changes reflected in your hosted docker build?

**Comment by dabeeeenster** [comment]
Next 5 minutes!

**Pull request merged**
